# Generated by Django 5.2.8 on 2025-11-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_rename_department_name_department_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='quickstart.employee'),
        ),
    ]
